{% set name = "picologging" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/picologging-{{ version }}.tar.gz
  sha256: 720788043b677a49aea47fae8013988bbc1af2cd0df05e884b3e285f71423e18

build:
  skip: true  # [(py<37) or (python_impl == 'pypy')]
  script:
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools >=42
  host:
    - cmake >=3.18
    - ninja
    - pip
    - python
    - scikit-build >=0.13
  run:
    - python

test:
  imports:
    - picologging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/picologging
  summary: A fast and lightweight logging library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
